logLevel: 7
logDir: "log"
logBaseFileName: "material-pass.log"
maxRetries: 3
variables:
  serverUrl: 'https://materialpass.int.demo.catena-x.net'
  providerUrl: 'https://materialpass.int.demo.catena-x.net/provider/api/v1/ids/data'
  apiKey: 'password'
