---
apiVersion: v2
name: edc
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: edc-controlplane
    alias: controlplane
    version: "0.2.0"
    repository: https://catenax-ng.github.io/product-edc
    condition: controlplane.enabled
  - name: edc-dataplane
    alias: dataplane
    version: "0.2.0"
    repository: https://catenax-ng.github.io/product-edc
    condition: dataplane.enabled
  - name: backend-service
    version: "0.0.6"
    repository: file://backend-service
    alias: consumerbackendapplication
    condition: consumerbackendapplication.enabled
  - name: postgresql
    alias: postgres
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
