# Copyright 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-ui.fullname" . }}
  labels:
    {{- include "consumer-ui.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            - name: "VUE_APP_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  clientId
                  name: avp-consumer-ui-cx-registry-auth
            - name: "VUE_APP_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  clientSecret
                  name: avp-consumer-ui-cx-registry-auth
            - name: "X_API_KEY"
              valueFrom:
                secretKeyRef:
                  key:  xApiKey
                  name: avp-consumer-ui-edc-oauth
            - name: "BACKEND"
              value: "{{ .Values.avp.helm.backend }}"
              
            - name: "VERSION"
              value: "{{ .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
