apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: product-material-pass
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
