# Copyright 2023 BASF SE, BMW AG, Henkel AG & Co. KGaA
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LogUtil:
  level: 7 # 7 FOR INFO AND 8 FOR DEBUG
  async: false

maxRetries: 5

keycloak:
  tokenUri: 'https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token'

variables:
  default:
    providerUrl: 'https://materialpass.dev.demo.catena-x.net/provider/api/v1/ids/data'
    serverUrl: 'https://materialpass.dev.demo.catena-x.net'
    registryUrl: 'https://semantics.dev.demo.catena-x.net'

passport:
  versions:
    - 'v1'

vault:
  type: 'local'
  file: 'vault.token-dev.yml'
  uri: 'http://localhost:8200'
  pathSep: "."
  prettyPrint: true
  indent: 2
  defaultValue: '<Add secret value here>'
  attributes:
    - "token"
    - "client.id"
    - "client.secret"
    - "apiKey"
