import type MetaInterface from '@/interfaces/MetaInterface';
// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.4.2',
  date: '2023-02-10T10:15:14.564Z',
};
export default meta;
